name: ECore
author: Onenrico
version: 1.0
api-version: 1.13
main: me.onenrico.ecore.mainapi.APICore
softdepend: [CMI, Vault, PlaceholderAPI, WorldEdit, WorldGuard, PlayerPoints, Essentials,PermissionsEx,UltraPermissions]